.gitignore, README.md, app.py, buildmain.py, main.js, requirements.txt
Saw your posts on TikTok and really liked the idea so i wanted to help out and contribute some!
Quality of Life changes
* Added Python String Interpolation on buildmain.py to help with readability and hopefully to cut down on html errors.
* Added an gitingore.
* Added an requirements.txt with dependencies.
Moved the voice processing away from Say to [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis). This is a web browser native api which allows you to get away from the desktop/mac needed for this program. This makes the program full accesible from the web now. So you could move the project to Django/flash to have a python web application. Or can move it all to a Javascript frame work, drop python and have it ready to be made into a mobile app and webapp. …
=> Qol updates and Voice change

build.json, buildmain.py, main.js
Brought the JavaScript to a more modern standard and commented all the code as well, to further allow contribution from others.
=> Clean Up + Document JavaScript

CONTRIBUTING.md, README.md, main.js
Updated the JavaScript as discussed in #5 just to make it more safe in regards to JavaScript + Window loading.
I also pulled the CONTRIBUTING.md that was referred to in the README.md originally and copied it and modified it and added it to this repo just so that it can live in this repo.
=> JS Tweak + Contribution Guidelines

.github/workflows/build-and-publish.yml
adding this will for now just lint, since there's no tests,
I'll make another PR to automatically publish this to now.sh
related to issue #18
=> add basic ci

vueapp/package-lock.json, vueapp/package.json, vueapp/src/views/TilePad.vue
Fixes #23,
Changed from using the mobile-device-detect package to detect devices to using vuetify's [breakpoints](https://vuetifyjs.com/en/customization/breakpoints) to create a responsive view
=> switched from detecting mobile devices to detecting screen size

vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/src/store/modules/tilePad.js, vueapp/src/views/TilePad.vue
You can tap on the tiles to add them to the sentence and tap to remove them, then play the sentence using the Play button
=> added sentence building

README.md, docs/CONTRIBUTING.md
Added the original contributing guide back to the repo. Also added some changes to it to help new people coming to the project. Wanted to make sure you are good with the wording on everything @Merkie
=> Changes to Readme and added a more detail contributing guide

vueapp/src/components/Sentence/Sentence.vue
=> added icons to the speak and cancel buttons

vueapp/src/components/TilePad/Tile.vue, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue
=> move sentence toggle to settings

vueapp/package-lock.json, vueapp/package.json, vueapp/tests/unit/Tile.spec.js
This is just a base setup and a few tests on Tile.vue.
I think the tests can be fleshed out over time, and it's useful to get the base in ASAP so that other contributors can include tests in their PRs :)
Relates to #15
=> Base setup for unit tests

build.json, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/components/TilePad/Tile.vue
This pull request adds custom color selection using the `v-color-picker` Vuetify component. **Please note that you need to reset your LocalStorage for this to work properly. Changes were made to the build.json (adding default accent fields to every item) to make this work consistently**.
=> Add custom color selection.

vueapp/babel.config.js, vueapp/package.json, vueapp/src/App.vue, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/components/NumberPad/NumberPad.vue, vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/src/main.js, vueapp/src/plugins/vuetify.js, vueapp/src/registerServiceWorker.js, vueapp/src/router.js, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/store/store.js, vueapp/src/views/About.vue, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue, vueapp/tests/unit/NumberPad.spec.js, vueapp/tests/unit/Tile.spec.js, vueapp/vue.config.js
I added spacing formatting along with a few others via Eslint. I think Eslint is going be the way to go for this project. With eslint i can set up some GitHub actions to lint and notify the author of the PR that their is linting  differences so it saves me time and keeps the code formatted correctly. 
If i don't hear any major complaints by about mid day or a bit later i'll merge.
=> Spacing format, and other formatting by eslint

README.md, build.json, vueapp/.editorconfig, vueapp/babel.config.js, vueapp/package.json, vueapp/src/App.vue, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/components/NumberPad/NumberPad.vue, vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/src/main.js, vueapp/src/plugins/vuetify.js, vueapp/src/registerServiceWorker.js, vueapp/src/router.js, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/store/store.js, vueapp/src/views/About.vue, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue, vueapp/tests/unit/NumberPad.spec.js, vueapp/tests/unit/Tile.spec.js, vueapp/vue.config.js
Many IDEs will read this file, should help reduce issues like @samwightt is having in #53
=> Add .editorconfig so that many IDEs will know to use 2 spaces for indent

.gitignore, build.json, vueapp/.editorconfig, vueapp/package-lock.json, vueapp/package.json, vueapp/src/App.vue, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/components/NumberPad/NumberPad.vue, vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/src/i18n.js, vueapp/src/locales/de.json, vueapp/src/locales/en.json, vueapp/src/main.js, vueapp/src/registerServiceWorker.js, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/views/About.vue, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue, vueapp/tests/unit/Tile.spec.js, vueapp/vue.config.js
This adds multi-language support both for application strings (e.g. labels in settings page) and tiles.
Also includes German strings for the default tiles, which work when a German voice is selected.
=> Multilingual support, German texts

README.md, vueapp/.editorconfig, vueapp/babel.config.js, vueapp/package.json, vueapp/src/App.vue, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/components/NumberPad/NumberPad.vue, vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/src/main.js, vueapp/src/plugins/vuetify.js, vueapp/src/registerServiceWorker.js, vueapp/src/router.js, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/store/store.js, vueapp/src/views/About.vue, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue, vueapp/tests/unit/NumberPad.spec.js, vueapp/tests/unit/Tile.spec.js, vueapp/vue.config.js
=> Reset button that clears localStorage and reloads

.github/workflows/build-and-publish.yml, .github/workflows/pull-request.yml, vueapp/package.json
Also changes the build job to only run on pushes to `master` and adds caching of node_modules (for faster running of actions)
=> Lint and test on pull request

vueapp/src/components/TilePad/Tile.vue, vueapp/src/views/Settings.vue
Got code base back to a linted state. Should all be automatically checked from here on out.
=> Linted code

vueapp/package-lock.json, vueapp/src/components/Sentence/Sentence.vue, vueapp/src/components/TilePad/Tile.vue, vueapp/tests/unit/Tile.spec.js
This should solve issue #74 along with created a test for it so it hopefully does not happen again.
=> Fixed issue #74 and created test for it

vueapp/vue.config.js
Adding these settings will allow people using a headless server to start testing and developing on this project.
=> Add headless server development settings

README.md
Extra sections added to include more detail as requested in issue #83
=> Update to README.md (#83)

.gitignore, vueapp/babel.config.js, vueapp/package-lock.json, vueapp/package.json, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/store/modules/settings.js, vueapp/src/views/TilePad.vue, vueapp/tests/unit/EditModeHeader.spec.js, vueapp/tests/unit/Sentence.spec.js, vueapp/tests/unit/Tile.spec.js
* Adds a bit more unit testing
* Upgrades the projects npm packages. Including going to Vue Cli 4.
=> Added Unit Tests and Npms upgrades

build.json, vueapp/src/components/EditModeHeader/EditModeHeader.vue, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/locales/en.json, vueapp/src/locales/sp.json, vueapp/tests/unit/EditModeHeader.spec.js
- Add missing translation in Spanish
- Move static text to en.json & sp.json
=> Add missing translations in spanish

vueapp/src/components/TilePad/Tile.vue, vueapp/src/locales/en.json, vueapp/src/locales/sp.json, vueapp/src/store/modules/settings.js, vueapp/src/store/modules/tilePad.js, vueapp/src/views/Settings.vue, vueapp/src/views/TilePad.vue, vueapp/tests/unit/tilePad.spec.js
Add tap counter. tap will be counted until user clicks on Speak button
#32
=> Tap counter

build.json
This adds a button named "Tiles" in the Keyboard Folder that allows the user to go back to the Tiles Folder.
=> Add "Tiles" button in Keyboard Folder 

README.md, vueapp/package-lock.json, vueapp/src/components/TilePad/EditTileDialog.vue, vueapp/src/views/TilePad.vue
* Fixed the save function
* Remove add new tile for now. Needs work
* Removed my Ko-Fi link. I no longer need financial support. and feel wrong leaving it there with the project gaining traction again.
With all the new attention the project is getting someone reached out to me that they were having a bug with saving and editing. I removed the add new tile button since it does not work currently and made sure the edit worked. Should be working a bit better. Here is the message from the person who originally raised the issue.
=> Fixed save function

vueapp/src/components/TilePad/EditTileDialog.vue
This solves issue #115 
This is my solution to this issue, this is how it was working before the fix:
https://user-images.githubusercontent.com/63618776/147006956-b27a90a8-0c3c-43e1-b86c-5914b11929e9.mov
This is how it is working after the fix:
https://user-images.githubusercontent.com/63618776/147006998-5515e147-9289-4651-89ec-e170ff07fafc.mov
To solve this issue I changed the null expression to an empty expression.
=> Tile-clear-navigation

astro.config.mjs, package.json, src/components/app/SentenceBuilder.svelte, src/components/app/Tile.svelte, src/lib/client/stores.ts, yarn.lock
- sentence builder stuff
- add vercel
=> 170 add sentence creation
